from .simclr import SIMCLR
from .elrg import ELRG
from .synaptic_intelligence import SynapticIntelligence
from .fisher_estimation import FisherEstimation
from .parameter_regularization.param_distance import ParamDistance
from .parameter_regularization.mixup import Mixup
from .parameter_regularization.vcl import VCL
from .function_regularization.rdl import RDL
from .function_regularization.frcl import FRCL
from .function_regularization.fromp import FROMP
from .function_regularization.knowledge_distillation import KnowledgeDistillation
from .function_regularization.attention_transfer import AttentionTransfer
from .function_regularization.equivariance_transfer import EquivarianceTransfer
from .function_regularization.function_distance import FunctionDistance
